provider:
    name: openfaas

functions:
  sample-func-with-secret:
    lang: dockerfile
    skip_build: true
    image: functions/api-key-protected:latest
    environment:
      fprocess: cat /var/openfaas/secrets/my-secret
    annotations:
      com.github.neuroforgede.nf-faas-docker.additionalNetworks: additional_network
    secrets:
    - my-secret